import { Project } from './types';

export const projects: Project[] = [
  {
    "id": 1,
    "slug": "americinn-pampa",
    "brand": "AmericInn by Wyndham",
    "location": "Pampa, Texas",
    "description": "Complete guestroom casegoods, soft seating, and brand-approved decorative lighting upgrades.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/1.webp",
    "hoverImagePath": "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/2.webp",
    "keysCount": "80 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/1.webp",
      "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/2.webp",
      "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/3.webp",
      "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/4.webp",
      "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/5.webp",
      "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/6.webp",
      "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/7.webp",
      "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/8.webp",
      "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/9.webp",
      "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/10.webp",
      "/Our Potfolio/AmericInn by Wyndham Pampa Event Center, Texas/11.webp"
    ],
    "narrative": [
      "For the AmericInn by Wyndham in Pampa, Texas, we executed a comprehensive FF&E procurement package tailored to meet Wyndham's updated brand guidelines.",
      "Our team managed the direct manufacturing and logistics of all guestroom casegoods, including custom headboards, nightstands, and study desks. We also provided high-durability contract seating and modern, energy-efficient light fixtures.",
      "By value engineering materials and shipping directly from the factory, we optimized the client's budget, achieving a successful franchise PIP clearance with zero punch list items."
    ]
  },
  {
    "id": 2,
    "slug": "best-western-montrose",
    "brand": "Best Western",
    "location": "Montrose, Colorado",
    "description": "Turnkey lobby renovation, public area custom millwork, and guestroom seating upgrades.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/1.webp",
    "hoverImagePath": "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/2.webp",
    "keysCount": "52 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/1.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/2.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/3.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/4.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/5.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/6.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/7.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/8.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/9.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/10.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/11.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/12.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/13.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/14.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/15.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/16.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/17.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/18.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/19.webp",
      "/Our Potfolio/Best Western Montrose Inn, Montrose, CO/20.webp"
    ],
    "narrative": [
      "The Best Western Montrose Inn project required a dramatic upgrade to the public areas and lobby, aligning the property with contemporary guest expectations.",
      "We manufactured and delivered bespoke lobby lounge seating, custom reception desks, and decorative wood paneling. The guestroom package featured upgraded ergonomic seating and custom vanity bases.",
      "Working closely with the ownership group and designers, we consolidated all shipments at a regional warehouse and managed just-in-time delivery to coordinate with the on-site contractor's schedule."
    ]
  },
  {
    "id": 3,
    "slug": "best-western-post",
    "brand": "Best Western",
    "location": "Post, Texas",
    "description": "Coordinated guestroom and lobby FF&E procurement with custom-fabricated casegoods.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Best Western Post Inn, Texas/1.webp",
    "hoverImagePath": "/Our Potfolio/Best Western Post Inn, Texas/2.webp",
    "keysCount": "60 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Best Western Post Inn, Texas/1.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/2.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/3.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/4.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/5.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/6.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/7.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/8.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/9.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/10.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/11.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/12.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/13.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/14.webp",
      "/Our Potfolio/Best Western Post Inn, Texas/15.webp"
    ],
    "narrative": [
      "At the Best Western Post Inn, Texas, we completed a full guestroom furniture replacement program focusing on durability and brand compliance.",
      "The scope included direct-source casegoods with high-pressure laminate tops, contract seating, and custom draperies. We also delivered coordinating public space seating for the breakfast area.",
      "Our factory-direct model allowed the client to bypass third-party markups, maximizing the return on investment and ensuring a seamless transition during the PIP audit."
    ]
  },
  {
    "id": 4,
    "slug": "comfort-inn-houston",
    "brand": "Comfort Inn & Suites",
    "location": "Houston, Texas",
    "description": "Turnkey guestroom furniture refresh and lobby millwork procurement for a premium PIP upgrade.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Comfort Inn & Suites Houston/1.webp",
    "hoverImagePath": "/Our Potfolio/Comfort Inn & Suites Houston/2.webp",
    "keysCount": "110 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Comfort Inn & Suites Houston/1.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/2.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/3.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/4.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/5.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/6.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/7.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/8.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/9.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/10.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/11.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/12.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/13.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/14.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/15.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/16.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/17.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/18.webp",
      "/Our Potfolio/Comfort Inn & Suites Houston/19.webp"
    ],
    "narrative": [
      "Located in Houston, Texas, this Comfort Inn & Suites project involved a complete guestroom casegoods package and lobby seating renovation.",
      "We fabricated custom headboards with integrated LED reading lights, nightstands with built-in power outlets, and sleek work desks. Lobby elements included modular sectional seating and architectural accents.",
      "Despite the project's scale, our team delivered all guestroom furniture in sequential phases, minimizing downtime and letting the hotel maintain occupancy throughout the renovation."
    ]
  },
  {
    "id": 5,
    "slug": "crossroads-huron",
    "brand": "Crossroads Hotel",
    "location": "Huron, South Dakota",
    "description": "Bespoke event center seating, custom lounge furniture, and custom boutique guestroom millwork.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/1.webp",
    "hoverImagePath": "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/2.webp",
    "keysCount": "100 Keys",
    "category": "concept",
    "gallery": [
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/1.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/2.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/3.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/4.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/5.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/6.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/7.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/8.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/9.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/10.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/11.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/12.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/13.webp",
      "/Our Potfolio/Crossroads Hotel-Huron Event Center, South Dakota/14.webp"
    ],
    "narrative": [
      "The Crossroads Hotel & Huron Event Center in South Dakota required custom furniture designed for high-traffic event use and comfortable guest rooms.",
      "We developed and procured custom banquet seating, modular lobby sofas, and tailored guestroom casegoods that reflect the unique local character of the property.",
      "Our team coordinated custom fabric selections and solid wood construction to ensure longevity, delivering a refined aesthetic that elevates both the guest rooms and the event experience."
    ]
  },
  {
    "id": 6,
    "slug": "everspring-bismarck",
    "brand": "EverSpring Inn",
    "location": "Bismarck, North Dakota",
    "description": "Turnkey public lounge seating, executive guestroom desks, and boutique lobby furniture.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/1.webp",
    "hoverImagePath": "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/2.webp",
    "keysCount": "125 Keys",
    "category": "concept",
    "gallery": [
      "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/1.webp",
      "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/2.webp",
      "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/3.webp",
      "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/4.webp",
      "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/5.webp",
      "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/6.webp",
      "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/7.webp",
      "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/8.webp",
      "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/9.webp",
      "/Our Potfolio/EverSpring Inn, Bismarck, ND, USA/10.webp"
    ],
    "narrative": [
      "The EverSpring Inn in Bismarck, ND, represents a major hospitality refresh focusing on upscale guestroom work environments and inviting community spaces.",
      "We manufactured custom executive desks, task chairs, and premium upholstered headboards. The public spaces were outfitted with large-scale sectional sofas and coordinating coffee tables.",
      "Through careful material curation and direct QA monitoring at the factories, we delivered a premium look that supports the EverSpring brand's regional expansion."
    ]
  },
  {
    "id": 7,
    "slug": "hampton-inn-st-louis",
    "brand": "Hampton Inn",
    "location": "Columbia, Illinois",
    "description": "Complete Hilton PIP guestroom compliance package and lobby accents.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/1.webp",
    "hoverImagePath": "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/2.webp",
    "keysCount": "85 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/1.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/2.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/3.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/4.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/5.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/6.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/7.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/8.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/9.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/10.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/11.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/12.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/13.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/14.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/15.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/16.webp",
      "/Our Potfolio/Hampton Inn St. Louis, Columbia - Illinois/17.webp"
    ],
    "narrative": [
      "Serving the St. Louis area, the Hampton Inn in Columbia, Illinois, required a complete FF&E refresh to meet Hilton's latest Forever Young Initiative standards.",
      "Our scope spanned guestroom casegoods, signature vanity bases, ergonomic desk chairs, and public area communal tables with built-in charging connectivity.",
      "Our logistics team coordinated cross-border transport and local warehousing to ensure a smooth, on-time delivery schedule, enabling the hotel to open renovated rooms ahead of schedule."
    ]
  },
  {
    "id": 8,
    "slug": "holiday-inn-express-waco",
    "brand": "Holiday Inn Express & Suites",
    "location": "West, Texas",
    "description": "IHG brand-compliant guestroom casegoods, seating, and blackout window treatments.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/1.webp",
    "hoverImagePath": "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/2.webp",
    "keysCount": "80 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/1.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/2.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/3.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/4.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/5.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/6.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/7.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/8.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/9.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/10.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/11.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/12.webp",
      "/Our Potfolio/Holiday Inn Express & Suites N Waco Area - West Texas/13.webp"
    ],
    "narrative": [
      "For the Holiday Inn Express & Suites N Waco Area in West, Texas, we procured a comprehensive Formula Blue PIP package.",
      "This included high-quality guestroom casegoods, custom lounge chairs, vanity mirrors, and premium blackout drapery. Public area furniture was also provided to match the brand's modern, bright lobby aesthetic.",
      "All manufactured pieces successfully passed IHG's strict quality assurance reviews, offering guests a fresh, comfortable, and brand-standard experience."
    ]
  },
  {
    "id": 9,
    "slug": "holiday-inn-express-fairhope",
    "brand": "Holiday Inn Express",
    "location": "Fairhope, Alabama",
    "description": "Premium guestroom casegoods and seating for a complete franchise PIP renovation.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/1.webp",
    "hoverImagePath": "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/2.webp",
    "keysCount": "84 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/1.webp",
      "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/2.webp",
      "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/3.webp",
      "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/4.webp",
      "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/5.webp",
      "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/6.webp",
      "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/7.webp",
      "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/8.webp",
      "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/9.webp",
      "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/10.webp",
      "/Our Potfolio/Holiday Inn Express Fairhope-Point Clear - Alabama/11.webp"
    ],
    "narrative": [
      "Located in the scenic Fairhope, Alabama area, this project involved executing a full IHG Formula Blue guestroom PIP renovation.",
      "We sourced and delivered modern guestroom casegoods, ergonomic task seating, accent chairs, and custom draperies. Every product was selected and engineered to offer superior durability and compliance.",
      "Our direct-sourcing model provided substantial cost savings to the client, delivering an elegant finish that was approved by IHG brand inspectors on the first audit."
    ]
  },
  {
    "id": 10,
    "slug": "country-inn-pierre",
    "brand": "Country Inn & Suites",
    "location": "Pierre, South Dakota",
    "description": "Custom oak-finish headboards, nightstands, dressers, and desks designed to meet Radisson's brand standards.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/1.webp",
    "hoverImagePath": "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/2.webp",
    "keysCount": "75 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/1.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/2.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/3.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/4.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/5.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/6.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/7.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/8.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/9.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/10.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/11.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/12.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/13.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/14.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/15.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/16.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/17.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/18.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/19.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/20.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/21.webp",
      "/Our Potfolio/Country Inn & Suites, Pierre, South Dakota/22.webp"
    ],
    "narrative": [
      "For the Country Inn & Suites in Pierre, South Dakota, we manufactured and delivered custom guestroom casegoods compliant with Radisson design regulations.",
      "The package featured durable oak-veneer writing desks, nightstands with integrated power hubs, luggage benches, and tailored headboards.",
      "By optimizing manufacturing processes and direct-shipping to the site, we ensured seamless PIP compliance and met the brand requirements on schedule."
    ]
  },
  {
    "id": 11,
    "slug": "quality-inn-bemidji",
    "brand": "Quality Inn",
    "location": "Bemidji, Minnesota",
    "description": "Heavy-duty guestroom desks, matching nightstands, and upholstered lounge seating built for high-occupancy guest use.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Quality Inn, Bemidji, MN/1.webp",
    "hoverImagePath": "/Our Potfolio/Quality Inn, Bemidji, MN/2.webp",
    "keysCount": "80 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Quality Inn, Bemidji, MN/1.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/2.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/3.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/4.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/5.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/6.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/7.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/8.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/9.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/10.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/11.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/12.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/13.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/14.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/15.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/16.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/17.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/18.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/19.webp",
      "/Our Potfolio/Quality Inn, Bemidji, MN/20.webp"
    ],
    "narrative": [
      "For the Quality Inn in Bemidji, Minnesota, we procured a comprehensive guestroom PIP package focusing on comfort and brand standard compliance.",
      "Our factory-direct casegoods, nightstands, and lounge chairs were manufactured using high-pressure laminate tops and moisture-resistant cores for long-term durability.",
      "This cost-effective sourcing solution allowed the property owners to bypass traditional markup expenses, completing the PIP cycle on budget."
    ]
  },
  {
    "id": 12,
    "slug": "springhill-suites-washington",
    "brand": "SpringHill Suites",
    "location": "Washington, Pennsylvania",
    "description": "Sleek contemporary media panels, floating desks, and integrated smart-wardrobes conforming to Marriott's brand specifications.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/1.webp",
    "hoverImagePath": "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/2.webp",
    "keysCount": "96 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/1.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/2.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/3.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/4.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/5.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/6.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/7.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/8.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/9.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/10.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/11.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/12.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/13.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/14.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/15.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/16.webp",
      "/Our Potfolio/Springhill Suites by Marriott, Washington, PA/17.webp"
    ],
    "narrative": [
      "For the SpringHill Suites in Washington, Pennsylvania, we manufactured custom modular suites casegoods reflecting Marriott's upscale aesthetic.",
      "Our scope included floating desks, bespoke media panels with integrated LED backlighting, upholstered accent seating, and sleek wardrobe units.",
      "The final products passed Marriott's strict QA inspections, delivering a modern, clean, and highly functional room layout on time."
    ]
  },
  {
    "id": 13,
    "slug": "hampton-inn-farmington",
    "brand": "Hampton Inn",
    "location": "Farmington, Missouri",
    "description": "Custom quartz-top guestroom vanities, headboards with integrated reading light mounts, and ergonomic armchairs.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Hampton Inn Farmington, MO/1.webp",
    "hoverImagePath": "/Our Potfolio/Hampton Inn Farmington, MO/2.webp",
    "keysCount": "85 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Hampton Inn Farmington, MO/1.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/2.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/3.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/4.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/5.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/6.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/7.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/8.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/9.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/10.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/11.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/12.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/13.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/14.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/15.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/16.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/17.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/18.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/19.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/20.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/21.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/22.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/23.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/24.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/25.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/26.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/27.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/28.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/29.webp",
      "/Our Potfolio/Hampton Inn Farmington, MO/30.webp"
    ],
    "narrative": [
      "The Hampton Inn Farmington, Missouri, project required dynamic guestroom FF&E updates to satisfy Hilton's modern brand standards.",
      "We produced custom quartz-top desk vanities, bed headboards, luggage benches, and ergonomic seating solutions.",
      "Our sequential production schedule allowed rooms to be renovated and returned to service in blocks, protecting the hotel's revenue flow during the process."
    ]
  },
  {
    "id": 14,
    "slug": "quality-inn-fort-pierre",
    "brand": "Quality Inn",
    "location": "Fort Pierre, South Dakota",
    "description": "Lobby reception desks, common area credenzas, and custom-styled guestroom furniture packages.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/1.webp",
    "hoverImagePath": "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/2.webp",
    "keysCount": "70 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/1.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/2.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/3.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/4.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/5.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/6.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/7.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/8.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/9.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/10.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/11.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/12.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/13.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/14.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/15.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/16.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/17.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/18.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/19.webp",
      "/Our Potfolio/Quality Inn Pierre – Fort Pierre, South Dakota/20.webp"
    ],
    "narrative": [
      "For the Quality Inn Pierre in Fort Pierre, South Dakota, we manufactured and shipped lobby millwork and custom guestroom casegoods.",
      "Key deliverables included main lobby reception counters, lounge area storage units, and durable guestroom headboards, nightstands, and writing desks.",
      "All items were built utilizing premium, high-wear materials to satisfy Choice Hotels brand criteria, passing audit on the first inspection."
    ]
  },
  {
    "id": 15,
    "slug": "holiday-inn-mobile",
    "brand": "Holiday Inn",
    "location": "Mobile, Alabama",
    "description": "Comprehensive guestroom furniture solutions, functional wardrobes, and accent seating customized to IHG brand layouts.",
    "isPlaceholder": false,
    "imagePath": "/Our Potfolio/Holiday Inn Mobile - Alabama/1.webp",
    "hoverImagePath": "/Our Potfolio/Holiday Inn Mobile - Alabama/2.webp",
    "keysCount": "115 Keys",
    "category": "pip",
    "gallery": [
      "/Our Potfolio/Holiday Inn Mobile - Alabama/1.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/2.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/3.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/4.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/5.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/6.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/7.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/8.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/9.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/10.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/11.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/12.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/13.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/14.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/15.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/16.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/17.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/18.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/19.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/20.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/21.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/22.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/23.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/24.webp",
      "/Our Potfolio/Holiday Inn Mobile - Alabama/25.webp"
    ],
    "narrative": [
      "For the Holiday Inn Mobile, Alabama, we procured and fabricated custom guestroom casegoods and soft seating following IHG specifications.",
      "Our team managed production of headboards, nightstands, functional wardrobe closet units, and upholstered accent chairs.",
      "This package successfully modernized the hotel interior, offering a highly durable and appealing finish that met all IHG requirements."
    ]
  }
];

export const featuredProjects: Project[] = [
  {
    "id": 101,
    "slug": "holiday-inn",
    "brand": "Holiday Inn",
    "location": "Fairhope, Alabama",
    "description": "A full FF&E refresh delivered on brand standard and on schedule.",
    "isPlaceholder": false,
    "imagePath": "/projects/holiday-inn/holiday-inn.webp",
    "keysCount": "84 Keys",
    "category": "pip",
    "gallery": [
      "/projects/holiday-inn/holiday-inn.webp",
      "/projects/holiday-inn/Screenshot 2026-06-19 172132.webp",
      "/projects/holiday-inn/Screenshot 2026-06-20 021503.webp",
      "/projects/holiday-inn/Screenshot 2026-06-19 172205.webp",
      "/projects/holiday-inn/Screenshot 2026-06-20 021529.webp",
      "/projects/holiday-inn/Screenshot 2026-06-20 021554.webp",
      "/projects/holiday-inn/Screenshot 2026-06-19 144959.webp",
      "/projects/holiday-inn/Screenshot 2026-06-19 172109.webp",
      "/projects/holiday-inn/Screenshot 2026-06-20 021449.webp"
    ]
  },
  {
    "id": 102,
    "slug": "hilton",
    "brand": "Hilton",
    "location": "Farmington, Missouri",
    "description": "Complete lobby, guestroom casegoods, and custom soft seating procurement.",
    "isPlaceholder": false,
    "imagePath": "/projects/hilton/Hilton.webp",
    "keysCount": "92 Keys",
    "category": "concept",
    "gallery": [
      "/projects/hilton/Hilton.webp",
      "/projects/hilton/Screenshot 2026-06-19 172655.webp",
      "/projects/hilton/Screenshot 2026-06-20 022129.webp",
      "/projects/hilton/Screenshot 2026-06-20 022150.webp",
      "/projects/hilton/Screenshot 2026-06-20 022203.webp",
      "/projects/hilton/Screenshot 2026-06-19 172735.webp",
      "/projects/hilton/Screenshot 2026-06-19 172742.webp",
      "/projects/hilton/Screenshot 2026-06-20 022116.webp",
      "/projects/hilton/Screenshot 2026-06-20 022140.webp"
    ]
  },
  {
    "id": 103,
    "slug": "comfort-inn-suites",
    "brand": "Comfort Inn & Suites",
    "location": "Bemidji, Minnesota",
    "description": "Value engineering and direct sourcing for guestroom PIP compliance.",
    "isPlaceholder": false,
    "imagePath": "/projects/comfort-inn/comfort-inn-suites.webp",
    "keysCount": "78 Keys",
    "category": "pip",
    "gallery": [
      "/projects/comfort-inn/comfort-inn-suites.webp",
      "/projects/comfort-inn/Screenshot 2026-06-20 021449.webp",
      "/projects/comfort-inn/Screenshot 2026-06-20 021529.webp",
      "/projects/comfort-inn/hero-4.jpeg",
      "/projects/comfort-inn/hero-8.jpeg",
      "/projects/comfort-inn/Screenshot 2026-06-19 172843.webp",
      "/projects/comfort-inn/Screenshot 2026-06-19 173101.webp"
    ]
  },
  {
    "id": 104,
    "slug": "marriott",
    "brand": "Marriott",
    "location": "Atlanta, Georgia",
    "description": "Luxury guestroom casegoods and public area custom millwork installation.",
    "isPlaceholder": false,
    "imagePath": "/projects/marriot/marriot.avif",
    "keysCount": "150 Keys",
    "category": "concept",
    "gallery": [
      "/projects/marriot/marriot.avif",
      "/projects/marriot/Screenshot 2026-06-20 021905.webp",
      "/projects/marriot/Screenshot 2026-06-20 021915.webp",
      "/projects/marriot/Screenshot 2026-06-20 021929.webp",
      "/projects/marriot/Screenshot 2026-06-19 171927.webp",
      "/projects/marriot/Screenshot 2026-06-19 172836.webp",
      "/projects/marriot/Screenshot 2026-06-19 172843.webp",
      "/projects/marriot/Screenshot 2026-06-19 172901.webp",
      "/projects/marriot/Screenshot 2026-06-20 021939.webp",
      "/projects/marriot/Screenshot 2026-06-20 021953.webp",
      "/projects/marriot/Screenshot 2026-06-20 022005.webp"
    ]
  },
  {
    "id": 105,
    "slug": "la-quinta",
    "brand": "La Quinta Inn & Suites",
    "location": "Austin, Texas",
    "description": "Value engineered PIP guestroom casegoods and seating.",
    "isPlaceholder": false,
    "imagePath": "/projects/la-quinta/la-quinta.jpeg",
    "keysCount": "88 Keys",
    "category": "pip",
    "gallery": [
      "/projects/la-quinta/la-quinta.jpeg",
      "/projects/la-quinta/Screenshot 2026-06-20 022545.webp",
      "/projects/la-quinta/Screenshot 2026-06-20 022554.webp",
      "/projects/la-quinta/Screenshot 2026-06-20 022625.webp",
      "/projects/la-quinta/Screenshot 2026-06-19 172221.webp",
      "/projects/la-quinta/Screenshot 2026-06-19 172249.webp",
      "/projects/la-quinta/Screenshot 2026-06-19 172304.webp",
      "/projects/la-quinta/Screenshot 2026-06-20 022536.webp"
    ]
  },
  {
    "id": 106,
    "slug": "candlewood-suites",
    "brand": "Candlewood Suites",
    "location": "Dallas, Texas",
    "description": "Turnkey extended-stay guestroom kitchenettes and casegoods procurement.",
    "isPlaceholder": false,
    "imagePath": "/projects/candelwood/candelwood-suites.webp",
    "keysCount": "94 Keys",
    "category": "pip",
    "gallery": [
      "/projects/candelwood/candelwood-suites.webp",
      "/projects/candelwood/Screenshot 2026-06-20 021611.webp",
      "/projects/candelwood/Screenshot 2026-06-20 021814.webp",
      "/projects/candelwood/Screenshot 2026-06-19 173119.webp",
      "/projects/candelwood/Screenshot 2026-06-19 173128.webp"
    ]
  },
  {
    "id": 107,
    "slug": "country-inn-suites",
    "brand": "Country Inn & Suites",
    "location": "Charlotte, North Carolina",
    "description": "Modern guestroom casegoods and public lounge upgrades.",
    "isPlaceholder": false,
    "imagePath": "/projects/country-inn/country-inn-suites.webp",
    "keysCount": "82 Keys",
    "category": "pip",
    "gallery": [
      "/projects/country-inn/country-inn-suites.webp",
      "/projects/country-inn/Screenshot 2026-06-20 022327.webp",
      "/projects/country-inn/Screenshot 2026-06-20 022408.webp",
      "/projects/country-inn/Screenshot 2026-06-20 022417.webp",
      "/projects/country-inn/Screenshot 2026-06-19 171927.webp",
      "/projects/country-inn/Screenshot 2026-06-19 172527.webp",
      "/projects/country-inn/Screenshot 2026-06-19 172540.webp"
    ]
  }
];
